In [4]:
import pandas as pd

energy_path = '../data/generated/gen-electricity-sources.csv'
emissions_path = '../data/generated/gen_emissions (1850-2022).csv'

energy = pd.read_csv(energy_path)
emissions = pd.read_csv(emissions_path)

# Filtrar colunas relevantes
emissions_cols = ['Entity', 'Year', 'Total (CO₂)', 'Coal (CO₂)', 'Oil (CO₂)', 'Gas (CO₂)']
energy_cols = ['Entity', 'Year', 'Coal (TWh)', 'Gas (TWh)', 'Oil (TWh)', 'Nuclear (TWh)', 'Hydro (TWh)', 'Solar (TWh)', 'Wind (TWh)']

merged = pd.merge(
    emissions[emissions_cols],
    energy[energy_cols],
    on=['Entity', 'Year'],
    how='inner'
)

merged.to_csv('../data/generated/final-dataset.csv', index=False)

In [5]:
merged

,Entity,Year,Total (CO₂),Coal (CO₂),Oil (CO₂),Gas (CO₂),Coal (TWh),Gas (TWh),Oil (TWh),Nuclear (TWh),Hydro (TWh),Solar (TWh),Wind (TWh)
0,Afghanistan,2000,1047128.0,3664.0,787760.0,223504.0,0.00,0.0,0.17,0.0,0.31,0.00,0.0
1,Afghanistan,2001,1069098.0,69616.0,762112.0,208848.0,0.04,0.0,0.15,0.0,0.50,0.00,0.0
2,Afghanistan,2002,1340995.0,55109.0,727438.0,547416.0,0.04,0.0,0.11,0.0,0.56,0.00,0.0
3,Afghanistan,2003,1559602.0,91813.0,991575.0,466408.0,0.09,0.0,0.19,0.0,0.63,0.00,0.0
4,Afghanistan,2004,1237247.0,91600.0,908672.0,227168.0,0.06,0.0,0.17,0.0,0.56,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7213,Zimbabwe,2018,10714598.0,6096896.0,4059712.0,0.0,4.13,0.0,0.05,0.0,5.05,0.01,0.0
7214,Zimbabwe,2019,9775428.0,5571349.0,3731338.0,0.0,4.05,0.0,0.05,0.0,4.17,0.02,0.0
7215,Zimbabwe,2020,7849639.0,4308864.0,3044784.0,0.0,2.74,0.0,0.04,0.0,3.81,0.02,0.0
7216,Zimbabwe,2021,8419980.0,4548245.0,3340869.0,0.0,2.51,0.0,0.00,0.0,5.93,0.02,0.0
7217,Zimbabwe,2022,8874823.0,5027008.0,3316950.0,0.0,2.92,0.0,0.00,0.0,5.88,0.03,0.0